# Generated by Django 3.2.19 on 2023-06-22 14:36

from django.db import migrations

from core.utils import insert_role_right_for_system


class Migration(migrations.Migration):
    dependencies = [
        ('tasks_management', '0001_initial'),
    ]

    operations = [

    ]
